# Generated by Django 2.2.1 on 2019-12-12 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import account.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdLoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_type', models.CharField(choices=[('wechat', '微信'), ('microblog', '微博'), ('qq', 'QQ'), ('others', '其他')], default='others', max_length=50)),
                ('openid', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=50)),
                ('logout', models.BooleanField(default=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('third_user_pic', models.ImageField(blank=True, height_field='image_height', null=True, upload_to=account.models.third_user_pic_upload, width_field='image_width')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ThirdPartyInfo',
                'verbose_name_plural': 'ThirdPartyInfos',
            },
        ),
        migrations.DeleteModel(
            name='ThirdPartyInfo',
        ),
    ]
