# Generated by Django 2.2.1 on 2019-12-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('secret', '保密')], default='secret', max_length=50),
        ),
    ]
