# Generated by Django 2.2.1 on 2019-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191214_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdlogininfo',
            name='openid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
