# Generated by Django 2.2.1 on 2019-12-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adinfo',
            old_name='url',
            new_name='link_url',
        ),
        migrations.AlterField(
            model_name='adinfo',
            name='location',
            field=models.CharField(choices=[('carousel', '动态轮播图'), ('personal_center', '个人中心')], max_length=20),
        ),
    ]
