# Generated by Django 2.2.1 on 2019-12-20 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_as_first_msgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_as_second_msgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
