# Generated by Django 2.2.1 on 2019-12-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_channelname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelname',
            old_name='chanel_name',
            new_name='channel_name',
        ),
    ]
