# Generated by Django 2.2.1 on 2019-12-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_auto_20191218_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
