# Generated by Django 2.2.1 on 2019-12-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_blockuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockuser',
            old_name='blocking',
            new_name='owner',
        ),
    ]
