# Generated by Django 2.2.1 on 2019-12-22 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0006_followuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('customer_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FeedBack',
                'verbose_name_plural': 'FeedBacks',
            },
        ),
    ]
