# Generated by Django 2.2.1 on 2019-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
