# Generated by Django 2.2.1 on 2019-12-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20191213_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='content.Topic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Article'),
        ),
    ]
