# Generated by Django 2.2.1 on 2019-12-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20191213_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(choices=[('follow ', '关注'), ('recommends', '推荐'), ('sports', '体育'), ('hot ', '热点'), ('finance', '财经'), ('share', '娱乐')], unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('image', '图文'), ('video', '视频'), ('share', '分享转发')], max_length=10),
        ),
    ]
