# Generated by Django 2.2.1 on 2019-12-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20191214_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_pic',
        ),
    ]
