# Generated by Django 2.2.1 on 2019-12-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_post_title_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_pic',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
