# Generated by Django 2.2.1 on 2019-12-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_post_title_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='share_post',
        ),
        migrations.AddField(
            model_name='post',
            name='share_post',
            field=models.ManyToManyField(blank=True, null=True, related_name='_post_share_post_+', to='content.Post'),
        ),
    ]
