# Generated by Django 2.2.1 on 2019-12-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20191216_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(choices=[('follow', '关注'), ('recommends', '推荐'), ('sports', '体育'), ('hot', '热点'), ('finance', '财经'), ('entertainment', '娱乐')], unique=True),
        ),
    ]
