# Generated by Django 2.2.1 on 2019-12-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20191217_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
