# Generated by Django 2.2.1 on 2019-12-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20191217_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
