# Generated by Django 2.2.1 on 2019-12-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20191218_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='share_post',
            field=models.ManyToManyField(blank=True, related_name='_post_share_post_+', to='content.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(blank=True, to='content.Topic'),
        ),
    ]
