# Generated by Django 2.2.1 on 2019-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male ', '男'), ('female', '女'), ('secret', '保密')], default='secret', max_length=50),
        ),
    ]
