# Generated by Django 2.2.1 on 2019-12-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191212_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thirdlogininfo',
            options={'verbose_name': 'ThirdLoginInfo', 'verbose_name_plural': 'ThirdLoginInfos'},
        ),
    ]
