# Generated by Django 2.2.1 on 2019-10-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191012_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logout',
            field=models.BooleanField(default=True),
        ),
    ]
