# Generated by Django 2.2.1 on 2019-10-09 14:22

from django.db import migrations, models
import login.validators


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191009_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(max_length=50, validators=[login.validators.validate_mobile_phone]),
        ),
    ]
