# Generated by Django 2.2.1 on 2019-10-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191009_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hometown',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
