# Generated by Django 2.2.1 on 2019-10-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20191012_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logout',
            field=models.BooleanField(default=False),
        ),
    ]
